import json
import os
from dataclasses import dataclass

import requests


@dataclass
class ReleaseItem:
    version: str
    linux_amd64_checksum: str
    darwin_amd64_checksum: str
    linux_arm64_checksum: str | None = None
    darwin_arm64_checksum: str | None = None


def main():
    items = fetch_release_items()
    generate_sdk_list(items)


def fetch_release_items():
    if "GH_ACCESS_TOKEN" not in os.environ:
        print(
            "You need to get an access token following the instructions in \n https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token"
        )
        exit(1)
    access_token = os.getenv("GH_ACCESS_TOKEN")
    releases_response = requests.get(
        "https://api.github.com/repos/kubernetes-sigs/kubebuilder/releases",
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"token {access_token}",
        },
    )

    items = []
    for release in releases_response.json():
        checksum_asset = [x for x in release["assets"] if x["name"] == "checksums.txt"][0]
        checksum_response = requests.get(checksum_asset["browser_download_url"])
        checksum_dic = checksum_text_to_dic(checksum_response.text)
        version_no_v = release["tag_name"].lstrip("v")

        def pick_checksum(os_id: str, arch_id: str):
            # Prefer legacy tarball filenames that include the version.
            legacy_name = f"kubebuilder_{version_no_v}_{os_id}_{arch_id}.tar.gz"
            if legacy_name in checksum_dic:
                return checksum_dic[legacy_name]

            # Fall back to v4+ plain binary filenames.
            binary_name = f"kubebuilder_{os_id}_{arch_id}"
            if binary_name in checksum_dic:
                return checksum_dic[binary_name]

            # Last resort: find a single sensible candidate containing the platform, excluding SBOM/JSON/signature files.
            candidates = [
                k
                for k in checksum_dic.keys()
                if f"_{os_id}_{arch_id}" in k
                and not k.endswith(".json")
                and ".sbom." not in k
                and not k.endswith(".sig")
            ]
            if len(candidates) == 1:
                return checksum_dic[candidates[0]]
            # Prefer tarballs if multiple
            tgz = [k for k in candidates if k.endswith(".tar.gz")]
            if tgz:
                return checksum_dic[tgz[0]]
            # Prefer exact binary name next
            if binary_name in candidates:
                return checksum_dic[binary_name]
            return None

        linux_amd64 = pick_checksum("linux", "amd64")
        darwin_amd64 = pick_checksum("darwin", "amd64")
        linux_arm64 = pick_checksum("linux", "arm64")
        darwin_arm64 = pick_checksum("darwin", "arm64")

        # Require amd64; arm64 optional
        if not linux_amd64 or not darwin_amd64:
            # Skip releases that don't conform to expected artifact layout
            continue

        items.append(
            ReleaseItem(
                release["tag_name"],
                linux_amd64,
                darwin_amd64,
                linux_arm64,
                darwin_arm64,
            )
        )

    return items


def generate_sdk_list(items: list[ReleaseItem]):
    result = """## Useful constants. Generated by generate_sdk_list.py

DEFAULT_VERSION = "4.8.0"

SDK_VERSION_SHA256 = {
"""
    sdk_dic = {}
    for item in items:
        entry = {
            "linux_amd64": item.linux_amd64_checksum,
            "darwin_amd64": item.darwin_amd64_checksum,
        }
        if item.linux_arm64_checksum:
            entry["linux_arm64"] = item.linux_arm64_checksum
        if item.darwin_arm64_checksum:
            entry["darwin_arm64"] = item.darwin_arm64_checksum
        sdk_dic[item.version.replace("v", "")] = entry
    result += remove_first_line(json.dumps(sdk_dic, indent=4))
    with open("sdk_list.bzl", "w") as f:
        f.write(result)
    print("output: sdk_list.bzl")


def checksum_text_to_dic(text):
    splitted_texts = text.split("\n")
    result = {}
    for pair in splitted_texts:
        split_pair = pair.split("  ")
        if len(split_pair) == 2:
            result[split_pair[1]] = split_pair[0]
    return result


def get_key_containing(keys, word):
    cands = [key for key in keys if word in key]
    if len(cands) == 1:
        return cands[0]
    return ""


def remove_first_line(text):
    tmp = text.split("\n")
    return "\n".join(tmp[1:])


if __name__ == "__main__":
    main()
